### PR TITLE
Add a custom input/output template option

### PR DESCRIPTION
**Pull request by ignaloidas**
Allows for some very funky balancer layouts, like for example, this 4-4 balancer
Screenshot_20230812_020520

### CODE REVIEW

**Comment by ignaloidas** [comment]
Hmm, doing it that way does have some pretty nice benefits, but I'm still not entirely sure on how the whole grid construction works (to get to this point I've mostly cobbled together what was already there), so I'd need to learn a bit more about that. I'll try to do that (not editing the jsons by hand would be pretty nice) but that's gonna take a bit.

**Comment by ignaloidas** [comment]
Alright, I updated it mostly in the way you proposed. Seems to work pretty nicely, for example here's a 4x5 balancer meant to split off a single lane off a bus, I only forced the top row to be empty and bus inputs and outputs, the split-off location chosen by SAT.

https://github.com/R-O-C-K-E-T/Factorio-SAT/assets/16557741/eaa56dc6-f69d-4d21-94ae-7649ecc60599

**Comment by R-O-C-K-E-T** [comment]
LGTM, if you can get it passing lint then I'll yeet it in.

It looks really good, thanks for fixing up some issues that have been annoyed me as well.

**Comment by ignaloidas** [comment]
Gah, thought I've ran lint, it appears not recently enough. Fixed it, should be good now.

**Pull request merged**
